export default {
  experience: [
    {
      date: "2017-05-01",
      company: "Westrock",
      image: "westrock.png",
      position: "Production Operations",
      type: "Co-op",
      timeline: "May 2017 - Aug 2017",
      range: "4 months",
      location: "Etobicoke, Ontario, Canada",
      roles: [
        "WestRock is a curragated packaging company",
        "I operated large machinery through control buttons",
        "I gained a strong fundemental understanding of safety procedures and protocols",
      ],
    },
    {
      date: "2018-05-01",
      company: "Survalent",
      image: "survalent.png",
      position: "IT Helpdesk",
      type: "Co-op",
      timeline: "May 2018 - Aug 2018",
      range: "4 months",
      location: "Brampton, Ontario, Canada",
      roles: [
        "Survalent is a software company that focuses on SCADA automation",
        "I presented live webinars to clients where I explained the new Service Level Agreements and answered any questions about the software",
        "I closed over 200 tickets within the time constraints as defined by the SLAs",
        "My favourite ticket was when I remoted into a live SCADA system to troubleshoot it",
      ],
    },
    {
      date: "2018-10-01",
      company: "McMaster University",
      image: "mcmaster.png",
      position: "Department of Computing and Software Ambassador",
      type: "Work Study",
      timeline: "Oct 2018 - Oct 2019",
      range: "13 months",
      location: "Hamilton, Ontario, Canada",
      roles: [
        "I represented the department of Software Engineering in recruitment events",
        "I answered questions that prospective highschool and first year engineering students had about the program",
        "I gave advice on university life and my personal anecdotes of my experience",
        "My favourite recruitment event was representing McMaster at the Ontario University Fair",
      ],
    },
    {
      date: "2019-01-01",
      company: "McMaster Children's Hospital",
      image: "mcmaster.png",
      position: "McMaster Children's Youth University Communications Assistant",
      type: "Work Study",
      timeline: "Jan 2019 - Apr 2019",
      range: "4 months",
      location: "Hamilton, Ontario, Canada",
      roles: [
        "McMaster Children's Youth University delivers free STEM and arts programming for children",
        "I was a communications assistant and designed all the digital posters, banners, and flyers",
        "I interviewed the youth who were involved in the program and wrote blog posts",
        "I created Powtoons animations for lecture introductions",
        "My favourite projects was designing the poster for Curiosity Crawl",
      ],
    },
    {
      date: "2019-05-01",
      company: "Embross",
      image: "Embross.png",
      position: "Software Developer",
      type: "Co-op",
      timeline: "May 2019 - Aug 2020",
      range: "16 months",
      location: "Richmond Hill, Ontario, Canada",
      roles: [
        "Embross is a company that focuses on automated self-service solutions",
        "I was part of the backend team and was able to develop in Java using Spring MVC and Javascript using NodeJS, and ReactJS",
        "I participated in a company hackathon where I was able to use ReactNative",
        "My favourite project was gathering customer requirements and implementing a loyalty program into the check-in kiosks",
      ],
    },
    {
      date: "2021-01-06",
      company: "McMaster University - Department of Engineering",
      image: "mcmaster.png",
      position: "Program Support Assistant",
      type: "Work Study",
      timeline: "Jan 2021 - Apr 2021",
      range: "4 months",
      location: "Hamilton, Ontario, Canada",
      roles: [
        "Awarded 3rd place in the Global Convergence Digital Inclusion Challenge 2020",
        "Lead the development of an iOS mobile application called i.AM that helps people with cognitive disabilities perform daily tasks",
        "Presented and networked with over 100 industry professionals to gather funding",
        "Used frameworks and tools such as React Native, Firebase, and TestFlight",
        "My favourite part of this project was testing the app directly with the target users and recieving real-time feedback",
      ],
    },
    // {
    //   date: "2021-06-28",
    //   company: "Microsoft",
    //   image: "microsoft.jpeg",
    //   position: "Software Engineer",
    //   type: "Full-Time",
    //   timeline: "June 2021 - Present",
    //   range: "Present",
    //   location: "Vancouver, British Columbia, Canada",
    //   roles: [
    //     "Incoming 2021 New Graduate"
    //   ],
    // },
  ],
}
